version: "3.8"

services:
  db:
    image: postgres:14-alpine
    container_name: pmtool-postgres
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: ./backend
    container_name: pmtool-node
    restart: always
    ports:
      - "3002:3000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app
      #- /usr/src/app/node_modules
    command: npm start

  frontend:
    build: ./frontend
    container_name: pmtool-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - app
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start

volumes:
  db_data:
