version: "3.8"

services:
  db:
    image: postgres:14-alpine
    container_name: pmtool-postgres
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./backend
    container_name: pmtool-node
    restart: always
    ports:
      - "3002:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    command: npm start
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    container_name: pmtool-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      app:
        condition: service_healthy
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start

volumes:
  db_data:
