version: "3.8"
services:
  testdb:
    image: postgres:14-alpine
    container_name: project-management-test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_management_test
    ports:
      - "5432:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data
volumes:
  test_db_data:
