version: "3.8"
services:
  testdb:
    image: postgres:14-alpine
    container_name: project-management-test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_management_test
    ports:
      - "5432:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data

  backend-test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: test
      DB_HOST: testdb
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: project_management_test
    depends_on:
      - testdb
    command: ["npm", "test"]

volumes:
  test_db_data:
